language: go
sudo: required
os: linux

go: "1.13.5"

# Strip debug symbols https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/
gobuild_args: -ldflags="-s -w"

jobs:
  include:
    # Config for building the linux x64 binary
    - os: linux
      env: OSNAME=linux GIMME_OS=linux GIMME_ARCH=amd64
    # Config for building the windows x64 binary
    - os: linux
      env: OSNAME=windows GIMME_OS=windows GIMME_ARCH=amd64 EXT=.exe
    # Config for building the macos x64 binary
    - os: linux
      env: OSNAME=macos GIMME_OS=darwin GIMME_ARCH=amd64


before_script: sudo apt-get -y install upx

script:
  - 'if [ -n "$TRAVIS_TAG" ]; then go build -o "backmeup_${OSNAME}_${GIMME_ARCH}_${TRAVIS_TAG}${EXT}" . && upx "backmeup_${OSNAME}_${GIMME_ARCH}_${TRAVIS_TAG}${EXT}"; else echo "Not building a tagged commit!" && go build; fi'

notifications:
  email: false

deploy:
  provider: releases
  api_key:
    secure: R1lxM1YgKRDAJFYbXwgxMkFVURj1kLua34D30EyuNlyK/M9vRTA4sXAJrdt34C6e4BK1+EiX/JI5Ng+46p43D+lQ2oxoKDS+Vz7l6Zt2fLQWo9Fi7JBFQhq6Rpz2Z0Hc0nQMV/M/NVYMRwTGT/l7EANTiHj76TGJgSFzVH7JJl/iemDOqcEGMcI99AnOiz7xYS3wx3KkF4C1v9H/89LynOSc34Yfvh2JOuLJwOwuSsa4+7k7NWCihniTh4O8mE+99LBEYoxqq40+Jq5A5PwT12rvzOrYtg99KOnNVAu7Z2iBgyNd/Uxurv69F6/910cdh7pwFrEX7TjeXT7zpWzSRlDnoD02zHS6qpUCRlUOrCIflZwAsvt17c5zfQ00tdCcaxqEEPrycymk9Nc3bnc6OhMq71jYdaFMtqYguGd1I3dvSPhn/lUYD94Y6vhMKuV+3yzx9DlsPH8tK3PSrEpc29W1iuV8kU0ZOEvDHSFL94+N7GJ/CVoxWIXpuMprrYfUc5AD1QRLEGHgVY1J4Tmp0vkwkDX4n/UsZngR2MzHArkhC7yyTxY/wRMJi1u1R3ORLLo/C9fm/0g3jlvdBiyKHLIXF4w+d0ugLgi0gk5sBM7DobFailkUERl1F8OVIMXXTwI4yAWhAiTm10UqLrkIQoTmvD61J+37uhjwS31pd84=
  file_glob: true
  file: "backmeup_*"
  skip_cleanup: true
  overwrite: true
  on:
    repo: d-Rickyy-b/backmeup
    tags: true